// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8BMQWhexbDFEnFL5P_XiPR1SETXLMumo',
    appId: '1:599784223139:web:f425e6d88dc70fc1562a16',
    messagingSenderId: '599784223139',
    projectId: 'products-65828',
    authDomain: 'products-65828.firebaseapp.com',
    storageBucket: 'products-65828.appspot.com',
    measurementId: 'G-XN0Z6TY0VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcKeYgDqOi85l-1lNc9WkPhg47nIVBmjw',
    appId: '1:599784223139:android:2915fed261de4b72562a16',
    messagingSenderId: '599784223139',
    projectId: 'products-65828',
    storageBucket: 'products-65828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe9lYV5GEgYLiaZOBXVxKyC4lxiighs70',
    appId: '1:599784223139:ios:b00522f18b6db6f6562a16',
    messagingSenderId: '599784223139',
    projectId: 'products-65828',
    storageBucket: 'products-65828.appspot.com',
    iosBundleId: 'com.example.flComponents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe9lYV5GEgYLiaZOBXVxKyC4lxiighs70',
    appId: '1:599784223139:ios:1589190350bfeecb562a16',
    messagingSenderId: '599784223139',
    projectId: 'products-65828',
    storageBucket: 'products-65828.appspot.com',
    iosBundleId: 'com.example.flComponents.RunnerTests',
  );
}
